# Generated by Django 4.0.4 on 2022-05-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_5', '0003_user_is_active_user_is_admin_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
