# Generated by Django 4.0.4 on 2022-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_5', '0004_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
